name: Continuous Delivery

on:
  push:
    branch: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Setup .npmrc file to publish to GitHub Packages
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@auth-plus'
      - name: Install dev packages
        run: npm ci
      - name: Install packages dependencies
        run: npm run bootstrap
      - name: Build
        run: npm run build
      - name: Configure CI Git User
        run: |
          git config --global user.email octobot@github.com
          git config --global user.name GitHub Actions
      - name: Publish package
        run: npm run publish -- --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

